### ISSUE TITLE
Admin password?

### ISSUE THREAD

**Issue by magthe** [ahaasler/docker-jira#2]
I'm trying out Jira using your Docker image, thank you very much for providing it!

One little issue though. Running and initial setup works beautifully, but then I land at a page where I'm supposed to log in but I don't know username and password for the administrator.

I've tried _admin_/_admin_ (which I understand is the default for some Atlassian products), but I'm not let in. If you've documented this I've completely failed to find it.

**Comment by ahaasler** [comment]
The [JIRA setup wizard](https://confluence.atlassian.com/jira/running-the-setup-wizard-185729463.html) gives you 2 setup options.

## Evaluation and demonstration setup

I'm able to create the admin user and set the password myself using the **I'll set it up myself** option in the Jira setup wizard:

![I'll set it up myself](https://cloud.githubusercontent.com/assets/1241721/12673487/59f9f216-c67d-11e5-8b69-e3042a3acf96.png)

## Production and testing setup

If you use the **Set it up for me** option instead, your login information is your Atlassian ID:

![Set it up for me screenshot](https://cloud.githubusercontent.com/assets/1241721/12673575/d8865372-c67d-11e5-87fa-55123179b809.png)

---

I have tested both methods and I it's working for me. If you continue to have this problem please reopen this issue.
