### ISSUE TITLE
Support JIRA 7 family

### ISSUE THREAD

**Issue by zugzug90** [ahaasler/docker-jira#3]
Add flag of JIRA version.
Depending on a version resolve correct URL to download binary distrib.

JIRA 7 is now renamed to JIRA CORE
Available via atlassian-jira-core- prefixed URL:
https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-core-7.2.0.tar.gz

**Comment by ahaasler** [comment]
This is already available on `latest`, `master` and `v7.0.0`. I'll try to catch up to version 7.2.0 over the weekend. I'll also create repositories for _Jira Software_ and _Jira Service Desk_.
